### PR TITLE
Text Map does not understand multiple headers under specific key

### PR DESCRIPTION
**Pull request by dgafka**
TEXT_MAP converter does not understand array under key. When we pass headers from request, they may be converted to array, even if there is only one value. 
This merge requests, solves this problem by extracting the value, if specific header is array.

### CODE REVIEW

**Comment by cawolf** [comment]
Hi, thank you for your contribution! :+1: 

It seems there is a copy-paste error in your PR, the variable `$carrier` does not exist.

Can you please provide a minimal example for your problem?

**Comment by dgafka** [comment]
Hello @cawolf

Good catch, I have fixed the code and provided test scenario. :)

**Comment by cawolf** [comment]
LGTM, can you fix the PHPStan issue?

```
> vendor/bin/phpstan analyse --no-progress
Note: Using configuration file /home/travis/build/auxmoney/OpentracingBundle-core/phpstan.neon.
 ------ ----------------------------------------------------------------- 
  Line   Internal/UtilityService.php                                      
 ------ ----------------------------------------------------------------- 
  23     Call to function is_array() with string will always evaluate to  
         false.                                                           
 ------ ----------------------------------------------------------------- 
 [ERROR] Found 1 error  
```

**Comment by cawolf** [comment]
FYI: I replace Travis CI with Github Actions to get this PR mergeable after you fixed the PHPStan issue.

**Comment by cawolf** [comment]
Hey @dgafka , did you find some time to fix the issue?

**Comment by cawolf** [comment]
I will close this PR for now due to no feedback. Feel free to reopen whenever you have time for it.

**Pull request closed without merging**
