### PR TITLE
fix: Move Trace-Propagation to Terminate Event

### PR DESCRIPTION
**Pull request by L3tum**
Hey there, I had noticed this when I was trying to overwrite some of the Controller Spanning for a Healthcheck Controller. Figured I would make a PR (and perhaps a few more) for it.

Is there a reason the trace flush was in the `finish_request` Event? That Event fires *before* the response is sent, making it less than ideal for this

### CODE REVIEW

**Comment by cawolf** [comment]
Hi @L3tum ,
thank you for your contribution!

I cannot remember the exact thought process of chosing `kernel.finish_request` over `kernel.terminate`, but I agree with you, that `kernel.terminate` is the better option.

Would you mind replacing `kernel.finish_request` entirely with `kernel.terminate`, instead of just adding the terminate event?

**Comment by cawolf** [comment]
I overlooked, that you deliberately separated `$this->tracing->finishActiveSpan();` and `$this->persistence->flush();` into the different events. This is actually a better solution than I proposed.

**Review by cawolf — APPROVED** [review]
LGTM

**Comment by L3tum** [comment]
Hey, thanks for merging this PR!

I'll probably make a few more in the coming weeks since my work is mandating the use of Jaeger and there doesn't seem to be a whole lot of Jaeger support in PHP. That is, aside from this collection of libraries^^

**Comment by cawolf** [comment]
You're welcome! Thank you for using this library and contributing to it to improve it :)

**Pull request merged**
